default: &default
  adapter: postgresql
  encoding: unicode
  host: ec2-54-91-188-254.compute-1.amazonaws.com
  port: 5432
  database: dcpt9ol8qg75ho
  pool:  5
  username: oocjupoqyzcfck
  password: 8c94f5a59a4f6539f5789867899da446d254cee85665ed12430e40efa64fec95

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
